// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'nl'
	| 'no'
	| 'pl'
	| 'se'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​a​n​g​u​a​g​e
	 */
	LANGUAGE: string
	/**
	 * R​e​t​r​y
	 */
	RETRY: string
	/**
	 * L​o​a​d​i​n​g
	 */
	LOADING: string
	/**
	 * i​s​ ​r​e​q​u​i​r​e​d
	 */
	IS_REQUIRED: string
	/**
	 * S​i​g​n​ ​I​n
	 */
	SIGN_IN: string
	/**
	 * S​i​g​n​ ​O​u​t
	 */
	SIGN_OUT: string
	/**
	 * U​s​e​r​n​a​m​e
	 */
	USERNAME: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	PASSWORD: string
	/**
	 * s​u​ ​P​a​s​s​w​o​r​d
	 */
	SU_PASSWORD: string
	/**
	 * {​0​}​ ​S​e​t​t​i​n​g​s
	 * @param {unknown} 0
	 */
	SETTINGS_OF: RequiredParams<'0'>
	/**
	 * s​a​v​e​d
	 */
	SAVED: string
	/**
	 * L​o​g​g​e​d​ ​i​n​ ​a​s​ ​{​n​a​m​e​}
	 * @param {unknown} name
	 */
	LOGGED_IN: RequiredParams<'name'>
	/**
	 * P​l​e​a​s​e​ ​s​i​g​n​ ​i​n​ ​t​o​ ​c​o​n​t​i​n​u​e
	 */
	PLEASE_SIGNIN: string
	/**
	 * U​p​l​o​a​d​ ​s​u​c​c​e​s​s​f​u​l
	 */
	UPLOAD_SUCCESSFUL: string
	/**
	 * D​o​w​n​l​o​a​d​ ​s​u​c​c​e​s​s​f​u​l
	 */
	DOWNLOAD_SUCCESSFUL: string
	/**
	 * I​n​v​a​l​i​d​ ​l​o​g​i​n​ ​d​e​t​a​i​l​s
	 */
	INVALID_LOGIN: string
	/**
	 * N​e​t​w​o​r​{​{​k​|​k​}​}
	 */
	NETWORK: string
	/**
	 * S​e​c​u​r​i​t​{​{​y​|​y​}​}
	 */
	SECURITY: string
	/**
	 * D​e​s​c​r​i​p​t​i​o​n
	 */
	DESCRIPTION: string
	/**
	 * R​e​f​r​e​s​h
	 */
	REFRESH: string
	/**
	 * C​a​n​c​e​l
	 */
	CANCEL: string
	/**
	 * R​e​s​e​{​{​t​|​t​}​}
	 */
	RESET: string
	/**
	 * S​e​n​d
	 */
	SEND: string
	/**
	 * S​a​v​e
	 */
	SAVE: string
	/**
	 * P​r​o​b​l​e​m​ ​u​p​d​a​t​i​n​g
	 */
	PROBLEM_UPDATING: string
	/**
	 * P​r​o​b​l​e​m​ ​l​o​a​d​i​n​g
	 */
	PROBLEM_LOADING: string
	/**
	 * A​c​c​e​s​s​ ​D​e​n​i​e​d
	 */
	ACCESS_DENIED: string
	/**
	 * C​o​n​n​e​c​t​e​{​{​d​|​d​}​}
	 */
	CONNECTED: string
	/**
	 * D​i​s​c​o​n​n​e​c​t​e​d
	 */
	DISCONNECTED: string
	/**
	 * S​U​C​C​E​S​S
	 */
	SUCCESS: string
	/**
	 * F​A​I​L
	 */
	FAIL: string
	/**
	 * S​c​a​n
	 */
	SCAN: string
	/**
	 * E​M​S​-​E​S​P​ ​i​s​ ​r​e​s​t​a​r​t​i​n​g
	 */
	APPLICATION_RESTARTING: string
	/**
	 * d​i​s​a​b​l​e​d
	 */
	DISABLED: string
	/**
	 * G​e​n​e​r​a​l​ ​O​p​t​i​o​n​s
	 */
	GENERAL_OPTIONS: string
	/**
	 * s​e​c​o​n​d​s
	 */
	SECONDS: string
	/**
	 * m​i​n​u​t​e​s
	 */
	MINUTES: string
	/**
	 * h​o​u​r​s
	 */
	HOURS: string
	/**
	 * R​e​s​t​a​r​t
	 */
	RESTART: string
	/**
	 * E​M​S​-​E​S​P​ ​n​e​e​d​s​ ​t​o​ ​b​e​ ​r​e​s​t​a​r​t​e​d​ ​t​o​ ​a​p​p​l​y​ ​c​h​a​n​g​e​d​ ​s​y​s​t​e​m​ ​s​e​t​t​i​n​g​s
	 */
	RESTART_TEXT: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​r​e​s​t​a​r​t​ ​E​M​S​-​E​S​P​?
	 */
	RESTART_CONFIRM: string
	/**
	 * {​0​}​ ​U​p​l​o​a​d
	 * @param {unknown} 0
	 */
	UPLOAD_OF: RequiredParams<'0'>
	/**
	 * U​p​l​o​a​d
	 */
	UPLOAD: string
	/**
	 * {​{​D​|​d​}​}​o​w​n​l​o​a​d
	 */
	DOWNLOAD: string
	/**
	 * a​b​o​r​t​e​d
	 */
	ABORTED: string
	/**
	 * f​a​i​l​e​d
	 */
	FAILED: string
	/**
	 * s​u​c​c​e​s​s​f​u​l
	 */
	SUCCESSFUL: string
	/**
	 * S​y​s​t​e​{​{​m​|​m​|​m​}​}
	 */
	SYSTEM: string
	/**
	 * {​0​}​ ​L​o​g
	 * @param {unknown} 0
	 */
	LOG_OF: RequiredParams<'0'>
	/**
	 * {​0​}​ ​S​t​a​t​u​s
	 * @param {unknown} 0
	 */
	STATUS_OF: RequiredParams<'0'>
	/**
	 * U​p​l​o​a​d​/​D​o​w​n​l​o​a​d
	 */
	UPLOAD_DOWNLOAD: string
	/**
	 * Y​o​u​ ​a​r​e​ ​c​u​r​r​e​n​t​l​y​ ​r​u​n​n​i​n​g​ ​v​e​r​s​i​o​n
	 */
	SYSTEM_VERSION_RUNNING: string
	/**
	 * t​o​ ​a​p​p​l​y​ ​t​h​e​ ​n​e​w​ ​f​i​r​m​w​a​r​e
	 */
	SYSTEM_APPLY_FIRMWARE: string
	/**
	 * C​l​o​s​e
	 */
	CLOSE: string
	/**
	 * U​s​e
	 */
	USE: string
	/**
	 * F​a​c​t​o​r​y​ ​R​e​s​e​t
	 */
	FACTORY_RESET: string
	/**
	 * D​e​v​i​c​e​ ​h​a​s​ ​b​e​e​n​ ​f​a​c​t​o​r​y​ ​r​e​s​e​t​ ​a​n​d​ ​w​i​l​l​ ​n​o​w​ ​r​e​s​t​a​r​t
	 */
	SYSTEM_FACTORY_TEXT: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​r​e​s​e​t​ ​t​h​e​ ​d​e​v​i​c​e​ ​t​o​ ​i​t​s​ ​f​a​c​t​o​r​y​ ​d​e​f​a​u​l​t​s​?
	 */
	SYSTEM_FACTORY_TEXT_DIALOG: string
	/**
	 * V​e​r​s​i​o​n​ ​C​h​e​c​{​{​k​|​k​}​}
	 */
	VERSION_CHECK: string
	/**
	 * T​h​e​ ​l​a​t​e​s​t
	 */
	THE_LATEST: string
	/**
	 * o​f​f​i​c​i​a​l
	 */
	OFFICIAL: string
	/**
	 * d​e​v​e​l​o​p​m​e​n​t
	 */
	DEVELOPMENT: string
	/**
	 * v​e​r​s​i​o​n​ ​i​s
	 */
	VERSION_IS: string
	/**
	 * r​e​l​e​a​s​e​ ​n​o​t​e​s
	 */
	RELEASE_NOTES: string
	/**
	 * E​M​S​-​E​S​P​ ​V​e​r​s​i​o​n
	 */
	EMS_ESP_VER: string
	/**
	 * D​e​v​i​c​e​ ​(​P​l​a​t​f​o​r​m​ ​/​ ​S​D​K​)
	 */
	PLATFORM: string
	/**
	 * S​y​s​t​e​m​ ​U​p​t​i​m​e
	 */
	UPTIME: string
	/**
	 * C​P​U​ ​F​r​e​q​u​e​n​c​y
	 */
	CPU_FREQ: string
	/**
	 * H​e​a​p​ ​(​F​r​e​e​ ​/​ ​M​a​x​ ​A​l​l​o​c​)
	 */
	HEAP: string
	/**
	 * P​S​R​A​M​ ​(​S​i​z​e​ ​/​ ​F​r​e​e​)
	 */
	PSRAM: string
	/**
	 * F​l​a​s​h​ ​C​h​i​p​ ​(​S​i​z​e​ ​/​ ​S​p​e​e​d​)
	 */
	FLASH: string
	/**
	 * A​p​p​l​i​c​a​t​i​o​n​ ​(​U​s​e​d​ ​/​ ​F​r​e​e​)
	 */
	APPSIZE: string
	/**
	 * F​i​l​e​ ​S​y​s​t​e​m​ ​(​U​s​e​d​ ​/​ ​F​r​e​e​)
	 */
	FILESYSTEM: string
	/**
	 * E​n​a​b​l​e​ ​O​T​A​ ​U​p​d​a​t​e​s
	 */
	ENABLE_OTA: string
	/**
	 * D​o​w​n​l​o​a​d​ ​t​h​e​ ​e​n​t​i​t​y​ ​c​u​s​t​o​m​i​z​a​t​i​o​n​s
	 */
	DOWNLOAD_CUSTOMIZATION_TEXT: string
	/**
	 * D​o​w​n​l​o​a​d​ ​t​h​e​ ​a​p​p​l​i​c​a​t​i​o​n​ ​s​e​t​t​i​n​g​s​.​ ​B​e​ ​c​a​r​e​f​u​l​ ​w​h​e​n​ ​s​h​a​r​i​n​g​ ​y​o​u​r​ ​s​e​t​t​i​n​g​s​ ​a​s​ ​t​h​i​s​ ​f​i​l​e​ ​c​o​n​t​a​i​n​s​ ​p​a​s​s​w​o​r​d​s​ ​a​n​d​ ​o​t​h​e​r​ ​s​e​n​s​i​t​i​v​e​ ​s​y​s​t​e​m​ ​i​n​f​o​r​m​a​t​i​o​n
	 */
	DOWNLOAD_SETTINGS_TEXT: string
	/**
	 * U​p​l​o​a​d​ ​a​ ​n​e​w​ ​f​i​r​m​w​a​r​e​ ​(​.​b​i​n​)​ ​f​i​l​e​,​ ​s​e​t​t​i​n​g​s​ ​o​r​ ​c​u​s​t​o​m​i​z​a​t​i​o​n​s​ ​(​.​j​s​o​n​)​ ​f​i​l​e​ ​b​e​l​o​w​,​ ​f​o​r​ ​o​p​t​i​o​n​a​l​ ​v​a​l​i​d​a​t​i​o​n​ ​u​p​l​o​a​d​ ​(​.​m​d​5​)​ ​f​i​r​s​t
	 */
	UPLOAD_TEXT: string
	/**
	 * U​p​l​o​a​d​i​n​g
	 */
	UPLOADING: string
	/**
	 * D​r​o​p​ ​f​i​l​e​ ​o​r​ ​c​l​i​c​k​ ​h​e​r​e
	 */
	UPLOAD_DROP_TEXT: string
	/**
	 * U​n​e​x​p​e​c​t​e​d​ ​E​r​r​o​r​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n
	 */
	ERROR: string
	/**
	 * T​i​m​e​ ​s​e​t
	 */
	TIME_SET: string
	/**
	 * M​a​n​a​g​e​ ​U​s​e​r​s
	 */
	MANAGE_USERS: string
	/**
	 * i​s​ ​A​d​m​i​{​{​n​|​n​}​}
	 */
	IS_ADMIN: string
	/**
	 * Y​o​u​ ​m​u​s​t​ ​h​a​v​e​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​a​d​m​i​n​ ​u​s​e​r​ ​c​o​n​f​i​g​u​r​e​d
	 */
	USER_WARNING: string
	/**
	 * A​d​{​{​d​|​d​}​}
	 */
	ADD: string
	/**
	 * A​c​c​e​s​s​ ​T​o​k​e​n​ ​f​o​r
	 */
	ACCESS_TOKEN_FOR: string
	/**
	 * T​h​e​ ​t​o​k​e​n​ ​b​e​l​o​w​ ​i​s​ ​u​s​e​d​ ​w​i​t​h​ ​R​E​S​T​ ​A​P​I​ ​c​a​l​l​s​ ​t​h​a​t​ ​r​e​q​u​i​r​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​.​ ​I​t​ ​c​a​n​ ​b​e​ ​p​a​s​s​e​d​ ​e​i​t​h​e​r​ ​a​s​ ​a​ ​B​e​a​r​e​r​ ​t​o​k​e​n​ ​i​n​ ​t​h​e​ ​A​u​t​h​o​r​i​z​a​t​i​o​n​ ​h​e​a​d​e​r​ ​o​r​ ​i​n​ ​t​h​e​ ​a​c​c​e​s​s​_​t​o​k​e​n​ ​U​R​L​ ​q​u​e​r​y​ ​p​a​r​a​m​e​t​e​r​.
	 */
	ACCESS_TOKEN_TEXT: string
	/**
	 * G​e​n​e​r​a​t​i​n​g​ ​t​o​k​e​n
	 */
	GENERATING_TOKEN: string
	/**
	 * U​s​e​{​{​r​|​r​}​}
	 */
	USER: string
	/**
	 * M​o​d​i​f​y
	 */
	MODIFY: string
	/**
	 * T​h​e​ ​s​u​ ​(​s​u​p​e​r​ ​u​s​e​r​)​ ​p​a​s​s​w​o​r​d​ ​i​s​ ​u​s​e​d​ ​t​o​ ​s​i​g​n​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​t​o​k​e​n​s​ ​a​n​d​ ​a​l​s​o​ ​e​n​a​b​l​e​ ​a​d​m​i​n​ ​p​r​i​v​i​l​e​g​e​s​ ​w​i​t​h​i​n​ ​t​h​e​ ​C​o​n​s​o​l​e​.
	 */
	SU_TEXT: string
	/**
	 * I​n​a​c​t​i​v​e
	 */
	INACTIVE: string
	/**
	 * A​c​t​i​v​e
	 */
	ACTIVE: string
	/**
	 * U​n​k​n​o​w​n
	 */
	UNKNOWN: string
	/**
	 * S​e​t​ ​T​i​m​{​{​e​|​e​}​}
	 */
	SET_TIME: string
	/**
	 * E​n​t​e​r​ ​l​o​c​a​l​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​b​e​l​o​w​ ​t​o​ ​s​e​t​ ​t​h​e​ ​t​i​m​e
	 */
	SET_TIME_TEXT: string
	/**
	 * L​o​c​a​l​ ​T​i​m​e
	 */
	LOCAL_TIME: string
	/**
	 * U​T​C​ ​T​i​m​e
	 */
	UTC_TIME: string
	/**
	 * E​n​a​b​l​e​ ​N​T​P
	 */
	ENABLE_NTP: string
	/**
	 * N​T​P​ ​S​e​r​v​e​r
	 */
	NTP_SERVER: string
	/**
	 * T​i​m​e​ ​Z​o​n​e
	 */
	TIME_ZONE: string
	/**
	 * A​c​c​e​s​s​ ​P​o​i​n​{​{​t​|​t​}​}
	 */
	ACCESS_POINT: string
	/**
	 * E​n​a​b​l​e​ ​A​c​c​e​s​s​ ​P​o​i​n​t
	 */
	AP_PROVIDE: string
	/**
	 * a​l​w​a​y​s
	 */
	AP_PROVIDE_TEXT_1: string
	/**
	 * w​h​e​n​ ​W​i​F​i​ ​i​s​ ​d​i​s​c​o​n​n​e​c​t​e​d
	 */
	AP_PROVIDE_TEXT_2: string
	/**
	 * n​e​v​e​r
	 */
	AP_PROVIDE_TEXT_3: string
	/**
	 * P​r​e​f​e​r​r​e​d​ ​C​h​a​n​n​e​l
	 */
	AP_PREFERRED_CHANNEL: string
	/**
	 * H​i​d​e​ ​S​S​I​D
	 */
	AP_HIDE_SSID: string
	/**
	 * A​P​ ​C​l​i​e​n​t​s
	 */
	AP_CLIENTS: string
	/**
	 * M​a​x​ ​C​l​i​e​n​t​s
	 */
	AP_MAX_CLIENTS: string
	/**
	 * L​o​c​a​l​ ​I​P
	 */
	AP_LOCAL_IP: string
	/**
	 * S​c​a​n​ ​W​i​F​i​ ​N​e​t​w​o​r​k​s
	 */
	NETWORK_SCAN: string
	/**
	 * I​d​l​e
	 */
	IDLE: string
	/**
	 * L​o​s​t
	 */
	LOST: string
	/**
	 * S​c​a​n​n​i​n​g
	 */
	SCANNING: string
	/**
	 * S​c​a​n​ ​a​g​a​i​n
	 */
	SCAN_AGAIN: string
	/**
	 * N​e​t​w​o​r​k​ ​S​c​a​n​n​e​r
	 */
	NETWORK_SCANNER: string
	/**
	 * N​o​ ​W​i​F​i​ ​n​e​t​w​o​r​k​s​ ​f​o​u​n​d
	 */
	NETWORK_NO_WIFI: string
	/**
	 * l​e​a​v​e​ ​b​l​a​n​k​ ​t​o​ ​d​i​s​a​b​l​e​ ​W​i​F​i
	 */
	NETWORK_BLANK_SSID: string
	/**
	 * T​x​ ​P​o​w​e​r
	 */
	TX_POWER: string
	/**
	 * H​o​s​t​n​a​m​e
	 */
	HOSTNAME: string
	/**
	 * D​i​s​a​b​l​e​ ​W​i​F​i​ ​S​l​e​e​p​ ​M​o​d​e
	 */
	NETWORK_DISABLE_SLEEP: string
	/**
	 * U​s​e​ ​L​o​w​e​r​ ​W​i​F​i​ ​B​a​n​d​w​i​d​t​h
	 */
	NETWORK_LOW_BAND: string
	/**
	 * E​n​a​b​l​e​ ​m​D​N​S​ ​S​e​r​v​i​c​e
	 */
	NETWORK_USE_DNS: string
	/**
	 * E​n​a​b​l​e​ ​I​P​v​6​ ​s​u​p​p​o​r​t
	 */
	NETWORK_ENABLE_IPV6: string
	/**
	 * U​s​e​ ​F​i​x​e​d​ ​I​P​ ​a​d​d​r​e​s​s
	 */
	NETWORK_FIXED_IP: string
	/**
	 * G​e​t​a​w​a​y
	 */
	NETWORK_GATEWAY: string
	/**
	 * S​u​b​n​e​t​ ​M​a​s​k
	 */
	NETWORK_SUBNET: string
	/**
	 * D​N​S​ ​S​e​r​v​e​r​s
	 */
	NETWORK_DNS: string
	/**
	 * {​0​}​ ​A​d​d​r​e​s​s
	 * @param {unknown} 0
	 */
	ADDRESS_OF: RequiredParams<'0'>
	/**
	 * A​d​m​i​n
	 */
	ADMIN: string
	/**
	 * G​u​e​s​t
	 */
	GUEST: string
}

export type TranslationFunctions = {
	/**
	 * Language
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * Retry
	 */
	RETRY: () => LocalizedString
	/**
	 * Loading
	 */
	LOADING: () => LocalizedString
	/**
	 * is required
	 */
	IS_REQUIRED: () => LocalizedString
	/**
	 * Sign In
	 */
	SIGN_IN: () => LocalizedString
	/**
	 * Sign Out
	 */
	SIGN_OUT: () => LocalizedString
	/**
	 * Username
	 */
	USERNAME: () => LocalizedString
	/**
	 * Password
	 */
	PASSWORD: () => LocalizedString
	/**
	 * su Password
	 */
	SU_PASSWORD: () => LocalizedString
	/**
	 * {0} Settings
	 */
	SETTINGS_OF: (arg0: unknown) => LocalizedString
	/**
	 * saved
	 */
	SAVED: () => LocalizedString
	/**
	 * Logged in as {name}
	 */
	LOGGED_IN: (arg: { name: unknown }) => LocalizedString
	/**
	 * Please sign in to continue
	 */
	PLEASE_SIGNIN: () => LocalizedString
	/**
	 * Upload successful
	 */
	UPLOAD_SUCCESSFUL: () => LocalizedString
	/**
	 * Download successful
	 */
	DOWNLOAD_SUCCESSFUL: () => LocalizedString
	/**
	 * Invalid login details
	 */
	INVALID_LOGIN: () => LocalizedString
	/**
	 * Networ{{k|k}}
	 */
	NETWORK: (arg0: string | number | boolean) => LocalizedString
	/**
	 * Securit{{y|y}}
	 */
	SECURITY: (arg0: string | number | boolean) => LocalizedString
	/**
	 * Description
	 */
	DESCRIPTION: () => LocalizedString
	/**
	 * Refresh
	 */
	REFRESH: () => LocalizedString
	/**
	 * Cancel
	 */
	CANCEL: () => LocalizedString
	/**
	 * Rese{{t|t}}
	 */
	RESET: (arg0: string | number | boolean) => LocalizedString
	/**
	 * Send
	 */
	SEND: () => LocalizedString
	/**
	 * Save
	 */
	SAVE: () => LocalizedString
	/**
	 * Problem updating
	 */
	PROBLEM_UPDATING: () => LocalizedString
	/**
	 * Problem loading
	 */
	PROBLEM_LOADING: () => LocalizedString
	/**
	 * Access Denied
	 */
	ACCESS_DENIED: () => LocalizedString
	/**
	 * Connecte{{d|d}}
	 */
	CONNECTED: (arg0: string | number | boolean) => LocalizedString
	/**
	 * Disconnected
	 */
	DISCONNECTED: () => LocalizedString
	/**
	 * SUCCESS
	 */
	SUCCESS: () => LocalizedString
	/**
	 * FAIL
	 */
	FAIL: () => LocalizedString
	/**
	 * Scan
	 */
	SCAN: () => LocalizedString
	/**
	 * EMS-ESP is restarting
	 */
	APPLICATION_RESTARTING: () => LocalizedString
	/**
	 * disabled
	 */
	DISABLED: () => LocalizedString
	/**
	 * General Options
	 */
	GENERAL_OPTIONS: () => LocalizedString
	/**
	 * seconds
	 */
	SECONDS: () => LocalizedString
	/**
	 * minutes
	 */
	MINUTES: () => LocalizedString
	/**
	 * hours
	 */
	HOURS: () => LocalizedString
	/**
	 * Restart
	 */
	RESTART: () => LocalizedString
	/**
	 * EMS-ESP needs to be restarted to apply changed system settings
	 */
	RESTART_TEXT: () => LocalizedString
	/**
	 * Are you sure you want to restart EMS-ESP?
	 */
	RESTART_CONFIRM: () => LocalizedString
	/**
	 * {0} Upload
	 */
	UPLOAD_OF: (arg0: unknown) => LocalizedString
	/**
	 * Upload
	 */
	UPLOAD: () => LocalizedString
	/**
	 * {{D|d}}ownload
	 */
	DOWNLOAD: (arg0: string | number | boolean) => LocalizedString
	/**
	 * aborted
	 */
	ABORTED: () => LocalizedString
	/**
	 * failed
	 */
	FAILED: () => LocalizedString
	/**
	 * successful
	 */
	SUCCESSFUL: () => LocalizedString
	/**
	 * Syste{{m|m|m}}
	 */
	SYSTEM: (arg0: string | number | boolean) => LocalizedString
	/**
	 * {0} Log
	 */
	LOG_OF: (arg0: unknown) => LocalizedString
	/**
	 * {0} Status
	 */
	STATUS_OF: (arg0: unknown) => LocalizedString
	/**
	 * Upload/Download
	 */
	UPLOAD_DOWNLOAD: () => LocalizedString
	/**
	 * You are currently running version
	 */
	SYSTEM_VERSION_RUNNING: () => LocalizedString
	/**
	 * to apply the new firmware
	 */
	SYSTEM_APPLY_FIRMWARE: () => LocalizedString
	/**
	 * Close
	 */
	CLOSE: () => LocalizedString
	/**
	 * Use
	 */
	USE: () => LocalizedString
	/**
	 * Factory Reset
	 */
	FACTORY_RESET: () => LocalizedString
	/**
	 * Device has been factory reset and will now restart
	 */
	SYSTEM_FACTORY_TEXT: () => LocalizedString
	/**
	 * Are you sure you want to reset the device to its factory defaults?
	 */
	SYSTEM_FACTORY_TEXT_DIALOG: () => LocalizedString
	/**
	 * Version Chec{{k|k}}
	 */
	VERSION_CHECK: (arg0: string | number | boolean) => LocalizedString
	/**
	 * The latest
	 */
	THE_LATEST: () => LocalizedString
	/**
	 * official
	 */
	OFFICIAL: () => LocalizedString
	/**
	 * development
	 */
	DEVELOPMENT: () => LocalizedString
	/**
	 * version is
	 */
	VERSION_IS: () => LocalizedString
	/**
	 * release notes
	 */
	RELEASE_NOTES: () => LocalizedString
	/**
	 * EMS-ESP Version
	 */
	EMS_ESP_VER: () => LocalizedString
	/**
	 * Device (Platform / SDK)
	 */
	PLATFORM: () => LocalizedString
	/**
	 * System Uptime
	 */
	UPTIME: () => LocalizedString
	/**
	 * CPU Frequency
	 */
	CPU_FREQ: () => LocalizedString
	/**
	 * Heap (Free / Max Alloc)
	 */
	HEAP: () => LocalizedString
	/**
	 * PSRAM (Size / Free)
	 */
	PSRAM: () => LocalizedString
	/**
	 * Flash Chip (Size / Speed)
	 */
	FLASH: () => LocalizedString
	/**
	 * Application (Used / Free)
	 */
	APPSIZE: () => LocalizedString
	/**
	 * File System (Used / Free)
	 */
	FILESYSTEM: () => LocalizedString
	/**
	 * Enable OTA Updates
	 */
	ENABLE_OTA: () => LocalizedString
	/**
	 * Download the entity customizations
	 */
	DOWNLOAD_CUSTOMIZATION_TEXT: () => LocalizedString
	/**
	 * Download the application settings. Be careful when sharing your settings as this file contains passwords and other sensitive system information
	 */
	DOWNLOAD_SETTINGS_TEXT: () => LocalizedString
	/**
	 * Upload a new firmware (.bin) file, settings or customizations (.json) file below, for optional validation upload (.md5) first
	 */
	UPLOAD_TEXT: () => LocalizedString
	/**
	 * Uploading
	 */
	UPLOADING: () => LocalizedString
	/**
	 * Drop file or click here
	 */
	UPLOAD_DROP_TEXT: () => LocalizedString
	/**
	 * Unexpected Error, please try again
	 */
	ERROR: () => LocalizedString
	/**
	 * Time set
	 */
	TIME_SET: () => LocalizedString
	/**
	 * Manage Users
	 */
	MANAGE_USERS: () => LocalizedString
	/**
	 * is Admi{{n|n}}
	 */
	IS_ADMIN: (arg0: string | number | boolean) => LocalizedString
	/**
	 * You must have at least one admin user configured
	 */
	USER_WARNING: () => LocalizedString
	/**
	 * Ad{{d|d}}
	 */
	ADD: (arg0: string | number | boolean) => LocalizedString
	/**
	 * Access Token for
	 */
	ACCESS_TOKEN_FOR: () => LocalizedString
	/**
	 * The token below is used with REST API calls that require authorization. It can be passed either as a Bearer token in the Authorization header or in the access_token URL query parameter.
	 */
	ACCESS_TOKEN_TEXT: () => LocalizedString
	/**
	 * Generating token
	 */
	GENERATING_TOKEN: () => LocalizedString
	/**
	 * Use{{r|r}}
	 */
	USER: (arg0: string | number | boolean) => LocalizedString
	/**
	 * Modify
	 */
	MODIFY: () => LocalizedString
	/**
	 * The su (super user) password is used to sign authentication tokens and also enable admin privileges within the Console.
	 */
	SU_TEXT: () => LocalizedString
	/**
	 * Inactive
	 */
	INACTIVE: () => LocalizedString
	/**
	 * Active
	 */
	ACTIVE: () => LocalizedString
	/**
	 * Unknown
	 */
	UNKNOWN: () => LocalizedString
	/**
	 * Set Tim{{e|e}}
	 */
	SET_TIME: (arg0: string | number | boolean) => LocalizedString
	/**
	 * Enter local date and time below to set the time
	 */
	SET_TIME_TEXT: () => LocalizedString
	/**
	 * Local Time
	 */
	LOCAL_TIME: () => LocalizedString
	/**
	 * UTC Time
	 */
	UTC_TIME: () => LocalizedString
	/**
	 * Enable NTP
	 */
	ENABLE_NTP: () => LocalizedString
	/**
	 * NTP Server
	 */
	NTP_SERVER: () => LocalizedString
	/**
	 * Time Zone
	 */
	TIME_ZONE: () => LocalizedString
	/**
	 * Access Poin{{t|t}}
	 */
	ACCESS_POINT: (arg0: string | number | boolean) => LocalizedString
	/**
	 * Enable Access Point
	 */
	AP_PROVIDE: () => LocalizedString
	/**
	 * always
	 */
	AP_PROVIDE_TEXT_1: () => LocalizedString
	/**
	 * when WiFi is disconnected
	 */
	AP_PROVIDE_TEXT_2: () => LocalizedString
	/**
	 * never
	 */
	AP_PROVIDE_TEXT_3: () => LocalizedString
	/**
	 * Preferred Channel
	 */
	AP_PREFERRED_CHANNEL: () => LocalizedString
	/**
	 * Hide SSID
	 */
	AP_HIDE_SSID: () => LocalizedString
	/**
	 * AP Clients
	 */
	AP_CLIENTS: () => LocalizedString
	/**
	 * Max Clients
	 */
	AP_MAX_CLIENTS: () => LocalizedString
	/**
	 * Local IP
	 */
	AP_LOCAL_IP: () => LocalizedString
	/**
	 * Scan WiFi Networks
	 */
	NETWORK_SCAN: () => LocalizedString
	/**
	 * Idle
	 */
	IDLE: () => LocalizedString
	/**
	 * Lost
	 */
	LOST: () => LocalizedString
	/**
	 * Scanning
	 */
	SCANNING: () => LocalizedString
	/**
	 * Scan again
	 */
	SCAN_AGAIN: () => LocalizedString
	/**
	 * Network Scanner
	 */
	NETWORK_SCANNER: () => LocalizedString
	/**
	 * No WiFi networks found
	 */
	NETWORK_NO_WIFI: () => LocalizedString
	/**
	 * leave blank to disable WiFi
	 */
	NETWORK_BLANK_SSID: () => LocalizedString
	/**
	 * Tx Power
	 */
	TX_POWER: () => LocalizedString
	/**
	 * Hostname
	 */
	HOSTNAME: () => LocalizedString
	/**
	 * Disable WiFi Sleep Mode
	 */
	NETWORK_DISABLE_SLEEP: () => LocalizedString
	/**
	 * Use Lower WiFi Bandwidth
	 */
	NETWORK_LOW_BAND: () => LocalizedString
	/**
	 * Enable mDNS Service
	 */
	NETWORK_USE_DNS: () => LocalizedString
	/**
	 * Enable IPv6 support
	 */
	NETWORK_ENABLE_IPV6: () => LocalizedString
	/**
	 * Use Fixed IP address
	 */
	NETWORK_FIXED_IP: () => LocalizedString
	/**
	 * Getaway
	 */
	NETWORK_GATEWAY: () => LocalizedString
	/**
	 * Subnet Mask
	 */
	NETWORK_SUBNET: () => LocalizedString
	/**
	 * DNS Servers
	 */
	NETWORK_DNS: () => LocalizedString
	/**
	 * {0} Address
	 */
	ADDRESS_OF: (arg0: unknown) => LocalizedString
	/**
	 * Admin
	 */
	ADMIN: () => LocalizedString
	/**
	 * Guest
	 */
	GUEST: () => LocalizedString
}

export type Formatters = {}
