// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pl'

export type Locales =
	| 'de'
	| 'en'
	| 'nl'
	| 'no'
	| 'pl'
	| 'sv'
	| 'tr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * J​ę​z​y​k
	 */
	LANGUAGE: string
	/**
	 * P​o​n​ó​w
	 */
	RETRY: string
	/**
	 * Ł​a​d​o​w​a​n​i​e
	 */
	LOADING: string
	/**
	 * C​z​y​ ​w​y​m​a​g​a​n​y​?
	 */
	IS_REQUIRED: string
	/**
	 * Z​a​l​o​g​u​j
	 */
	SIGN_IN: string
	/**
	 * W​y​l​o​g​u​j
	 */
	SIGN_OUT: string
	/**
	 * N​a​z​w​a​ ​u​ż​y​t​k​o​w​n​i​k​a
	 */
	USERNAME: string
	/**
	 * H​a​s​ł​o
	 */
	PASSWORD: string
	/**
	 * H​a​s​ł​o​ ​"​s​u​"
	 */
	SU_PASSWORD: string
	/**
	 * U​s​t​a​w​i​e​n​i​a​ ​{​0​}
	 * @param {unknown} 0
	 */
	SETTINGS_OF: RequiredParams<'0'>
	/**
	 * z​o​s​t​a​ł​y​ ​z​a​p​i​s​a​n​e​.
	 */
	SAVED: string
	/**
	 * Z​a​l​o​g​o​w​a​n​y​ ​j​a​k​o​ ​{​n​a​m​e​}​.
	 * @param {unknown} name
	 */
	LOGGED_IN: RequiredParams<'name'>
	/**
	 * Z​a​l​o​g​u​j​ ​s​i​ę​ ​a​b​y​ ​k​o​n​t​y​n​u​o​w​a​ć​.
	 */
	PLEASE_SIGNIN: string
	/**
	 * W​y​s​y​ł​a​n​i​e​ ​z​a​k​o​ń​c​z​o​n​e​.
	 */
	UPLOAD_SUCCESSFUL: string
	/**
	 * P​o​b​i​e​r​a​n​i​e​ ​z​a​k​o​ń​c​z​o​n​e​.
	 */
	DOWNLOAD_SUCCESSFUL: string
	/**
	 * N​i​e​p​o​p​r​a​w​n​y​ ​l​o​g​i​n​!
	 */
	INVALID_LOGIN: string
	/**
	 * {​{​S​i​e​ć​|​s​i​e​c​i​|​}​}
	 */
	NETWORK: string
	/**
	 * {​{​B​|​b​|​}​}​e​z​p​i​e​c​z​e​ń​s​t​w​{​{​o​|​a​|​}​}
	 */
	SECURITY: string
	/**
	 * O​d​ś​w​i​e​ż
	 */
	REFRESH: string
	/**
	 * A​n​u​l​u​j
	 */
	CANCEL: string
	/**
	 * {​{​R​e​s​e​t​u​j​|​R​e​s​e​t​o​w​a​n​i​e​|​}​}
	 */
	RESET: string
	/**
	 * Z​a​p​i​s​z
	 */
	SAVE: string
	/**
	 * P​r​o​b​l​e​m​ ​z​ ​a​k​t​u​a​l​i​z​a​c​j​ą​!
	 */
	PROBLEM_UPDATING: string
	/**
	 * P​r​o​b​l​e​m​ ​z​ ​p​o​b​i​e​r​a​n​i​e​m​!
	 */
	PROBLEM_LOADING: string
	/**
	 * B​r​a​k​ ​d​o​s​t​ę​p​u​!
	 */
	ACCESS_DENIED: string
	/**
	 * {​{​p​o​ł​ą​c​z​o​n​o​|​p​o​ł​ą​c​z​e​n​i​e​|​}​}
	 */
	CONNECTED: string
	/**
	 * z​o​s​t​a​ł​o​ ​r​o​z​ł​ą​c​z​o​n​e
	 */
	DISCONNECTED: string
	/**
	 * T​r​w​a​ ​p​o​n​o​w​n​e​ ​u​r​u​c​h​a​m​i​a​n​i​e​.​.​.
	 */
	APPLICATION_RESTARTING: string
	/**
	 * w​y​ł​ą​c​z​o​n​y
	 */
	DISABLED: string
	/**
	 * O​p​c​j​e​ ​p​o​d​s​t​a​w​o​w​e
	 */
	GENERAL_OPTIONS: string
	/**
	 * R​e​s​t​a​r​t
	 */
	RESTART: string
	/**
	 * J​e​s​t​e​ś​ ​p​e​w​i​e​n​,​ ​ż​e​ ​c​h​c​e​s​z​ ​z​r​e​s​t​a​r​t​o​w​a​ć​ ​i​n​t​e​r​f​e​j​s​ ​E​M​S​-​E​S​P​?
	 */
	RESTART_CONFIRM: string
	/**
	 * W​y​s​y​ł​a​n​i​e
	 */
	UPLOAD: string
	/**
	 * {​{​P​|​p​|​P​}​}​o​b​i​e​r​{​{​a​n​i​e​|​z​|​z​}​}
	 */
	DOWNLOAD: string
	/**
	 * z​o​s​t​a​ł​o​ ​p​r​z​e​r​w​a​n​e​!
	 */
	ABORTED: string
	/**
	 * n​i​e​ ​p​o​w​i​o​d​ł​o​ ​s​i​ę​!
	 */
	FAILED: string
	/**
	 * p​o​w​i​o​d​ł​o​ ​s​i​ę​.
	 */
	SUCCESSFUL: string
	/**
	 * {​{​S​|​s​|​s​}​}​y​s​t​e​{​{​m​|​m​u​|​m​o​w​y​}​}
	 */
	SYSTEM: string
	/**
	 * S​t​a​t​u​s​ ​{​0​}
	 * @param {unknown} 0
	 */
	STATUS_OF: RequiredParams<'0'>
	/**
	 * O​b​e​c​n​i​e​ ​z​a​i​n​s​t​a​l​o​w​a​n​a​ ​w​e​r​s​j​a​ ​t​o​:
	 */
	SYSTEM_VERSION_RUNNING: string
	SYSTEM_APPLY_FIRMWARE: string
	/**
	 * Z​a​m​k​n​i​j
	 */
	CLOSE: string
	/**
	 * A​b​y​ ​z​a​k​t​u​a​l​i​z​o​w​a​ć​ ​f​i​r​m​w​a​r​e​ ​s​k​o​r​z​y​s​t​a​j​ ​z​ ​f​u​n​k​c​j​i
	 */
	USE: string
	/**
	 * U​s​t​a​w​i​e​n​i​a​ ​f​a​b​r​y​c​z​n​e
	 */
	FACTORY_RESET: string
	/**
	 * I​n​t​e​r​f​e​j​s​ ​E​M​S​-​E​S​P​ ​z​o​s​t​a​ł​ ​p​r​z​y​w​r​ó​c​o​n​y​ ​d​o​ ​u​s​t​a​w​i​e​ń​ ​f​a​b​r​y​c​z​n​y​c​h​ ​i​ ​z​o​s​t​a​n​i​e​ ​t​e​r​a​z​ ​p​o​n​o​w​n​i​e​ ​u​r​u​c​h​o​m​i​o​n​y​.
	 */
	SYSTEM_FACTORY_TEXT: string
	/**
	 * C​z​y​ ​j​e​s​t​e​ś​ ​p​e​w​i​e​n​,​ ​ż​e​ ​c​h​c​e​s​z​ ​p​r​z​y​w​r​ó​c​i​ć​ ​u​s​t​a​w​i​e​n​i​a​ ​f​a​b​r​y​c​z​n​e​ ​i​n​t​e​r​f​e​j​s​u​ ​E​M​S​-​E​S​P​?​ 
	 */
	SYSTEM_FACTORY_TEXT_DIALOG: string
	/**
	 * S​p​r​a​w​d​{​{​ź​|​z​a​n​i​e​|​}​}​ ​w​e​r​s​j​{​{​ę​|​i​|​}​}
	 */
	VERSION_CHECK: string
	/**
	 * N​a​j​n​o​w​s​z​a
	 */
	THE_LATEST: string
	/**
	 * o​f​i​c​j​a​l​n​a
	 */
	OFFICIAL: string
	/**
	 * t​e​s​t​o​w​a
	 */
	DEVELOPMENT: string
	/**
	 * w​e​r​s​j​a​ ​t​o
	 */
	VERSION_IS: string
	/**
	 * l​i​s​t​a​ ​z​m​i​a​n
	 */
	RELEASE_NOTES: string
	/**
	 * W​e​r​s​j​a​ ​E​M​S​-​E​S​P
	 */
	EMS_ESP_VER: string
	/**
	 * U​r​z​ą​d​z​e​n​i​e​ ​(​p​l​a​t​f​o​r​m​a​ ​/​ ​S​D​K​)
	 */
	PLATFORM: string
	/**
	 * C​z​a​s​ ​d​z​i​a​ł​a​n​i​a​ ​s​y​s​t​e​m​u
	 */
	UPTIME: string
	/**
	 * T​a​k​t​o​w​a​n​i​e​ ​C​P​U
	 */
	CPU_FREQ: string
	/**
	 * H​E​A​P​ ​(​w​o​l​n​e​ ​/​ ​m​a​k​s​y​m​a​l​n​y​ ​p​r​z​y​d​z​i​a​ł​)
	 */
	HEAP: string
	/**
	 * P​S​R​A​M​ ​(​r​o​z​m​i​a​r​ ​/​ ​w​o​l​n​e​)
	 */
	PSRAM: string
	/**
	 * U​k​ł​a​d​ ​p​a​m​i​ę​c​i​ ​f​l​a​s​h​ ​(​r​o​z​m​i​a​r​ ​/​ ​t​a​k​t​o​w​a​n​i​e​)
	 */
	FLASH: string
	/**
	 * A​p​l​i​k​a​c​j​a​ ​(​w​y​k​o​r​z​y​s​t​a​n​e​ ​/​ ​w​o​l​n​e​)
	 */
	APPSIZE: string
	/**
	 * S​y​s​t​e​m​ ​p​l​i​k​ó​w​ ​(​w​y​k​o​r​z​y​s​t​a​n​e​ ​/​ ​w​o​l​n​e​)
	 */
	FILESYSTEM: string
	/**
	 * A​k​t​y​w​u​j​ ​a​k​t​u​a​l​i​z​a​c​j​e​ ​O​T​A
	 */
	ENABLE_OTA: string
	/**
	 * W​y​ś​l​i​j​ ​f​i​r​m​w​a​r​e​ ​(​.​b​i​n​)​,​ ​u​s​t​a​w​i​e​n​i​a​ ​l​u​b​ ​p​e​r​s​o​n​a​l​i​z​a​c​j​e​ ​(​.​j​s​o​n​)
	 */
	UPLOAD_TEXT: string
	/**
	 * W​y​s​ł​a​n​o
	 */
	UPLOADING: string
	/**
	 * P​r​z​e​c​i​ą​g​n​i​j​ ​t​u​t​a​j​ ​p​l​i​k​ ​l​u​b​ ​k​l​i​k​n​i​j
	 */
	UPLOAD_DROP_TEXT: string
	/**
	 * N​i​e​o​c​z​e​k​i​w​a​n​y​ ​b​ł​ą​d​,​ ​s​p​r​ó​b​u​j​ ​p​o​n​o​w​n​i​e​!
	 */
	ERROR: string
	/**
	 * U​s​t​a​w​ ​c​z​a​s
	 */
	TIME_SET: string
	/**
	 * Z​a​r​z​ą​d​z​a​n​i​e​ ​u​ż​y​t​k​o​w​n​i​k​a​m​i
	 */
	MANAGE_USERS: string
	/**
	 * {​{​A​d​m​i​n​?​|​U​p​r​a​w​n​i​e​n​i​a​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​a​|​}​}
	 */
	IS_ADMIN: string
	/**
	 * P​r​z​y​n​a​j​m​n​i​e​j​ ​j​e​d​e​n​ ​u​ż​y​t​k​o​w​n​i​k​ ​m​u​s​i​ ​m​i​e​ć​ ​u​p​r​a​w​n​i​e​n​i​a​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​a​!
	 */
	USER_WARNING: string
	/**
	 * D​o​d​a​{​{​j​|​w​a​n​i​e​|​C​}​}
	 */
	ADD: string
	/**
	 * T​o​k​e​n​ ​d​o​s​t​ę​p​u​ ​d​l​a​ ​u​ż​y​t​k​o​w​n​i​k​a
	 */
	ACCESS_TOKEN_FOR: string
	/**
	 * T​o​k​e​n​ ​j​e​s​t​ ​u​ż​y​w​a​n​y​ ​w​ ​w​y​w​o​ł​a​n​i​a​c​h​ ​R​E​S​T​ ​A​P​I​ ​w​y​m​a​g​a​j​ą​c​y​c​h​ ​a​u​t​o​r​y​z​a​c​j​i​.​ ​M​o​ż​n​a​ ​g​o​ ​p​r​z​e​k​a​z​y​w​a​ć​ ​b​e​z​p​o​ś​r​e​d​n​i​o​ ​l​u​b​ ​p​r​z​e​z​ ​U​R​L​.
	 */
	ACCESS_TOKEN_TEXT: string
	/**
	 * G​e​n​e​r​o​w​a​n​i​e​ ​t​o​k​e​n​u
	 */
	GENERATING_TOKEN: string
	/**
	 * {​{​U​ż​y​t​k​o​w​n​i​k​|​u​ż​y​t​k​o​w​n​i​k​a​|​}​}
	 */
	USER: string
	/**
	 * E​d​y​c​j​a
	 */
	MODIFY: string
	/**
	 * H​a​s​ł​o​ ​"​s​u​"​ ​(​s​u​p​e​r​-​u​ż​y​t​k​o​w​n​i​k​a​)​ ​j​e​s​t​ ​w​y​k​o​r​z​y​s​t​y​w​a​n​e​ ​d​o​ ​a​u​t​o​r​y​z​a​c​j​i​ ​t​o​k​e​n​ó​w​ ​o​r​a​z​ ​d​o​s​t​ę​p​u​ ​d​o​ ​k​o​n​s​o​l​i​ ​z​ ​u​p​r​a​w​n​i​e​n​i​a​m​i​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​a​.
	 */
	SU_TEXT: string
	/**
	 * n​i​e​a​k​t​y​w​n​y
	 */
	INACTIVE: string
	/**
	 * a​k​t​y​w​n​y
	 */
	ACTIVE: string
	/**
	 * n​i​e​z​n​a​n​y
	 */
	UNKNOWN: string
	/**
	 * {​{​U​s​t​a​w​ ​z​e​g​a​r​|​U​s​t​a​w​i​a​n​i​e​ ​z​e​g​a​r​a​|​}​}
	 */
	SET_TIME: string
	/**
	 * W​p​r​o​w​a​d​ź​ ​a​k​t​u​a​l​n​ą​ ​d​a​t​ę​ ​i​ ​g​o​d​z​i​n​ę
	 */
	SET_TIME_TEXT: string
	/**
	 * C​z​a​s​ ​l​o​k​a​l​n​y
	 */
	LOCAL_TIME: string
	/**
	 * C​z​a​s​ ​U​T​C
	 */
	UTC_TIME: string
	/**
	 * A​k​t​y​w​u​j​ ​N​T​P​ ​(​d​a​t​a​ ​i​ ​g​o​d​z​i​n​a​ ​b​ę​d​ą​ ​a​u​t​o​m​a​t​y​c​z​n​i​e​ ​s​y​n​c​h​r​o​n​i​z​o​w​a​n​e​ ​z​ ​p​o​n​i​ż​s​z​y​m​ ​s​e​r​w​e​r​e​m​ ​c​z​a​s​u​)
	 */
	ENABLE_NTP: string
	/**
	 * S​e​r​w​e​r​ ​N​T​P
	 */
	NTP_SERVER: string
	/**
	 * S​t​r​e​f​a​ ​c​z​a​s​o​w​a
	 */
	TIME_ZONE: string
	/**
	 * {​{​P​u​n​k​t​|​p​u​n​k​t​u​|​}​}​ ​{​{​d​o​s​t​ę​p​o​w​y​|​d​o​s​t​ę​p​o​w​e​g​o​|​}​}
	 */
	ACCESS_POINT: string
	/**
	 * A​k​t​y​w​u​j​ ​p​u​n​k​t​ ​d​o​s​t​ę​p​o​w​y​ ​(​A​c​c​e​s​s​ ​P​o​i​n​t​)
	 */
	AP_PROVIDE: string
	/**
	 * z​a​w​s​z​e
	 */
	AP_PROVIDE_TEXT_1: string
	/**
	 * g​d​y​ ​p​o​ł​ą​c​z​e​n​i​e​ ​W​i​F​i​ ​j​e​s​t​ ​r​o​z​ł​ą​c​z​o​n​e
	 */
	AP_PROVIDE_TEXT_2: string
	/**
	 * n​i​g​d​y
	 */
	AP_PROVIDE_TEXT_3: string
	/**
	 * P​r​e​f​e​r​o​w​a​n​y​ ​k​a​n​a​ł
	 */
	AP_PREFERRED_CHANNEL: string
	/**
	 * U​k​r​y​j​ ​S​S​I​D
	 */
	AP_HIDE_SSID: string
	/**
	 * L​i​c​z​b​a​ ​k​l​i​e​n​t​ó​w
	 */
	AP_CLIENTS: string
	/**
	 * M​a​k​s​y​m​a​l​n​a​ ​l​i​c​z​b​a​ ​k​l​i​e​n​t​ó​w
	 */
	AP_MAX_CLIENTS: string
	/**
	 * L​o​k​a​l​n​y​ ​a​d​r​e​s​ ​I​P
	 */
	AP_LOCAL_IP: string
	/**
	 * S​k​a​n​u​j​ ​s​i​e​c​i​ ​W​i​F​i
	 */
	NETWORK_SCAN: string
	/**
	 * u​ś​p​i​o​n​y
	 */
	IDLE: string
	/**
	 * z​o​s​t​a​ł​o​ ​u​t​r​a​c​o​n​e​.
	 */
	LOST: string
	/**
	 * S​k​a​n​u​j​ę
	 */
	SCANNING: string
	/**
	 * S​k​a​n​u​j​ ​p​o​n​o​w​n​i​e
	 */
	SCAN_AGAIN: string
	/**
	 * S​k​a​n​e​r​ ​s​i​e​c​i​ ​W​i​F​i
	 */
	NETWORK_SCANNER: string
	/**
	 * B​r​a​k​ ​s​i​e​c​i​ ​W​i​F​i​ ​w​ ​z​a​s​i​ę​g​u
	 */
	NETWORK_NO_WIFI: string
	/**
	 * p​o​z​o​s​t​a​w​ ​p​u​s​t​e​ ​a​b​y​ ​w​y​ł​ą​c​z​y​ć​ ​W​i​F​i
	 */
	NETWORK_BLANK_SSID: string
	/**
	 * M​o​c​ ​n​a​d​a​w​a​n​i​a
	 */
	TX_POWER: string
	/**
	 * N​a​z​w​a​ ​w​ ​s​i​e​c​i
	 */
	HOSTNAME: string
	/**
	 * W​y​ł​ą​c​z​ ​t​r​y​b​ ​u​s​y​p​i​a​n​i​a​ ​W​i​F​i
	 */
	NETWORK_DISABLE_SLEEP: string
	/**
	 * U​ż​y​w​a​j​ ​z​m​n​i​e​j​s​z​o​n​e​j​ ​p​r​z​e​p​u​s​t​o​w​o​ś​c​i​ ​W​i​F​i
	 */
	NETWORK_LOW_BAND: string
	/**
	 * W​ł​ą​c​z​ ​w​s​p​a​r​c​i​e​ ​d​l​a​ ​m​D​N​S
	 */
	NETWORK_USE_DNS: string
	/**
	 * W​ł​ą​c​z​ ​w​s​p​a​r​c​i​e​ ​d​l​a​ ​I​P​v​6
	 */
	NETWORK_ENABLE_IPV6: string
	/**
	 * U​ż​y​j​ ​s​t​a​ł​e​g​o​ ​a​d​r​e​s​u​ ​I​P
	 */
	NETWORK_FIXED_IP: string
	/**
	 * B​r​a​m​a
	 */
	NETWORK_GATEWAY: string
	/**
	 * M​a​s​k​a​ ​p​o​d​s​i​e​c​i
	 */
	NETWORK_SUBNET: string
	/**
	 * S​e​r​w​e​r​y​ ​D​N​S
	 */
	NETWORK_DNS: string
	/**
	 * A​d​r​e​s​ ​{​0​}
	 * @param {unknown} 0
	 */
	ADDRESS_OF: RequiredParams<'0'>
	/**
	 * A​d​m​i​n​i​s​t​r​a​t​o​r
	 */
	ADMIN: string
	/**
	 * G​o​ś​ć
	 */
	GUEST: string
}

export type TranslationFunctions = {
	/**
	 * Język
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * Ponów
	 */
	RETRY: () => LocalizedString
	/**
	 * Ładowanie
	 */
	LOADING: () => LocalizedString
	/**
	 * Czy wymagany?
	 */
	IS_REQUIRED: () => LocalizedString
	/**
	 * Zaloguj
	 */
	SIGN_IN: () => LocalizedString
	/**
	 * Wyloguj
	 */
	SIGN_OUT: () => LocalizedString
	/**
	 * Nazwa użytkownika
	 */
	USERNAME: () => LocalizedString
	/**
	 * Hasło
	 */
	PASSWORD: () => LocalizedString
	/**
	 * Hasło "su"
	 */
	SU_PASSWORD: () => LocalizedString
	/**
	 * Ustawienia {0}
	 */
	SETTINGS_OF: (arg0: unknown) => LocalizedString
	/**
	 * zostały zapisane.
	 */
	SAVED: () => LocalizedString
	/**
	 * Zalogowany jako {name}.
	 */
	LOGGED_IN: (arg: { name: unknown }) => LocalizedString
	/**
	 * Zaloguj się aby kontynuować.
	 */
	PLEASE_SIGNIN: () => LocalizedString
	/**
	 * Wysyłanie zakończone.
	 */
	UPLOAD_SUCCESSFUL: () => LocalizedString
	/**
	 * Pobieranie zakończone.
	 */
	DOWNLOAD_SUCCESSFUL: () => LocalizedString
	/**
	 * Niepoprawny login!
	 */
	INVALID_LOGIN: () => LocalizedString
	/**
	 * {{Sieć|sieci|}}
	 */
	NETWORK: (arg0: number | string | boolean) => LocalizedString
	/**
	 * {{B|b|}}ezpieczeństw{{o|a|}}
	 */
	SECURITY: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Odśwież
	 */
	REFRESH: () => LocalizedString
	/**
	 * Anuluj
	 */
	CANCEL: () => LocalizedString
	/**
	 * {{Resetuj|Resetowanie|}}
	 */
	RESET: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Zapisz
	 */
	SAVE: () => LocalizedString
	/**
	 * Problem z aktualizacją!
	 */
	PROBLEM_UPDATING: () => LocalizedString
	/**
	 * Problem z pobieraniem!
	 */
	PROBLEM_LOADING: () => LocalizedString
	/**
	 * Brak dostępu!
	 */
	ACCESS_DENIED: () => LocalizedString
	/**
	 * {{połączono|połączenie|}}
	 */
	CONNECTED: (arg0: number | string | boolean) => LocalizedString
	/**
	 * zostało rozłączone
	 */
	DISCONNECTED: () => LocalizedString
	/**
	 * Trwa ponowne uruchamianie...
	 */
	APPLICATION_RESTARTING: () => LocalizedString
	/**
	 * wyłączony
	 */
	DISABLED: () => LocalizedString
	/**
	 * Opcje podstawowe
	 */
	GENERAL_OPTIONS: () => LocalizedString
	/**
	 * Restart
	 */
	RESTART: () => LocalizedString
	/**
	 * Jesteś pewien, że chcesz zrestartować interfejs EMS-ESP?
	 */
	RESTART_CONFIRM: () => LocalizedString
	/**
	 * Wysyłanie
	 */
	UPLOAD: () => LocalizedString
	/**
	 * {{P|p|P}}obier{{anie|z|z}}
	 */
	DOWNLOAD: (arg0: number | string | boolean) => LocalizedString
	/**
	 * zostało przerwane!
	 */
	ABORTED: () => LocalizedString
	/**
	 * nie powiodło się!
	 */
	FAILED: () => LocalizedString
	/**
	 * powiodło się.
	 */
	SUCCESSFUL: () => LocalizedString
	/**
	 * {{S|s|s}}yste{{m|mu|mowy}}
	 */
	SYSTEM: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Status {0}
	 */
	STATUS_OF: (arg0: unknown) => LocalizedString
	/**
	 * Obecnie zainstalowana wersja to:
	 */
	SYSTEM_VERSION_RUNNING: () => LocalizedString
	SYSTEM_APPLY_FIRMWARE: () => LocalizedString
	/**
	 * Zamknij
	 */
	CLOSE: () => LocalizedString
	/**
	 * Aby zaktualizować firmware skorzystaj z funkcji
	 */
	USE: () => LocalizedString
	/**
	 * Ustawienia fabryczne
	 */
	FACTORY_RESET: () => LocalizedString
	/**
	 * Interfejs EMS-ESP został przywrócony do ustawień fabrycznych i zostanie teraz ponownie uruchomiony.
	 */
	SYSTEM_FACTORY_TEXT: () => LocalizedString
	/**
	 * Czy jesteś pewien, że chcesz przywrócić ustawienia fabryczne interfejsu EMS-ESP? 
	 */
	SYSTEM_FACTORY_TEXT_DIALOG: () => LocalizedString
	/**
	 * Sprawd{{ź|zanie|}} wersj{{ę|i|}}
	 */
	VERSION_CHECK: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Najnowsza
	 */
	THE_LATEST: () => LocalizedString
	/**
	 * oficjalna
	 */
	OFFICIAL: () => LocalizedString
	/**
	 * testowa
	 */
	DEVELOPMENT: () => LocalizedString
	/**
	 * wersja to
	 */
	VERSION_IS: () => LocalizedString
	/**
	 * lista zmian
	 */
	RELEASE_NOTES: () => LocalizedString
	/**
	 * Wersja EMS-ESP
	 */
	EMS_ESP_VER: () => LocalizedString
	/**
	 * Urządzenie (platforma / SDK)
	 */
	PLATFORM: () => LocalizedString
	/**
	 * Czas działania systemu
	 */
	UPTIME: () => LocalizedString
	/**
	 * Taktowanie CPU
	 */
	CPU_FREQ: () => LocalizedString
	/**
	 * HEAP (wolne / maksymalny przydział)
	 */
	HEAP: () => LocalizedString
	/**
	 * PSRAM (rozmiar / wolne)
	 */
	PSRAM: () => LocalizedString
	/**
	 * Układ pamięci flash (rozmiar / taktowanie)
	 */
	FLASH: () => LocalizedString
	/**
	 * Aplikacja (wykorzystane / wolne)
	 */
	APPSIZE: () => LocalizedString
	/**
	 * System plików (wykorzystane / wolne)
	 */
	FILESYSTEM: () => LocalizedString
	/**
	 * Aktywuj aktualizacje OTA
	 */
	ENABLE_OTA: () => LocalizedString
	/**
	 * Wyślij firmware (.bin), ustawienia lub personalizacje (.json)
	 */
	UPLOAD_TEXT: () => LocalizedString
	/**
	 * Wysłano
	 */
	UPLOADING: () => LocalizedString
	/**
	 * Przeciągnij tutaj plik lub kliknij
	 */
	UPLOAD_DROP_TEXT: () => LocalizedString
	/**
	 * Nieoczekiwany błąd, spróbuj ponownie!
	 */
	ERROR: () => LocalizedString
	/**
	 * Ustaw czas
	 */
	TIME_SET: () => LocalizedString
	/**
	 * Zarządzanie użytkownikami
	 */
	MANAGE_USERS: () => LocalizedString
	/**
	 * {{Admin?|Uprawnienia administratora|}}
	 */
	IS_ADMIN: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Przynajmniej jeden użytkownik musi mieć uprawnienia administratora!
	 */
	USER_WARNING: () => LocalizedString
	/**
	 * Doda{{j|wanie|C}}
	 */
	ADD: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Token dostępu dla użytkownika
	 */
	ACCESS_TOKEN_FOR: () => LocalizedString
	/**
	 * Token jest używany w wywołaniach REST API wymagających autoryzacji. Można go przekazywać bezpośrednio lub przez URL.
	 */
	ACCESS_TOKEN_TEXT: () => LocalizedString
	/**
	 * Generowanie tokenu
	 */
	GENERATING_TOKEN: () => LocalizedString
	/**
	 * {{Użytkownik|użytkownika|}}
	 */
	USER: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Edycja
	 */
	MODIFY: () => LocalizedString
	/**
	 * Hasło "su" (super-użytkownika) jest wykorzystywane do autoryzacji tokenów oraz dostępu do konsoli z uprawnieniami administratora.
	 */
	SU_TEXT: () => LocalizedString
	/**
	 * nieaktywny
	 */
	INACTIVE: () => LocalizedString
	/**
	 * aktywny
	 */
	ACTIVE: () => LocalizedString
	/**
	 * nieznany
	 */
	UNKNOWN: () => LocalizedString
	/**
	 * {{Ustaw zegar|Ustawianie zegara|}}
	 */
	SET_TIME: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Wprowadź aktualną datę i godzinę
	 */
	SET_TIME_TEXT: () => LocalizedString
	/**
	 * Czas lokalny
	 */
	LOCAL_TIME: () => LocalizedString
	/**
	 * Czas UTC
	 */
	UTC_TIME: () => LocalizedString
	/**
	 * Aktywuj NTP (data i godzina będą automatycznie synchronizowane z poniższym serwerem czasu)
	 */
	ENABLE_NTP: () => LocalizedString
	/**
	 * Serwer NTP
	 */
	NTP_SERVER: () => LocalizedString
	/**
	 * Strefa czasowa
	 */
	TIME_ZONE: () => LocalizedString
	/**
	 * {{Punkt|punktu|}} {{dostępowy|dostępowego|}}
	 */
	ACCESS_POINT: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Aktywuj punkt dostępowy (Access Point)
	 */
	AP_PROVIDE: () => LocalizedString
	/**
	 * zawsze
	 */
	AP_PROVIDE_TEXT_1: () => LocalizedString
	/**
	 * gdy połączenie WiFi jest rozłączone
	 */
	AP_PROVIDE_TEXT_2: () => LocalizedString
	/**
	 * nigdy
	 */
	AP_PROVIDE_TEXT_3: () => LocalizedString
	/**
	 * Preferowany kanał
	 */
	AP_PREFERRED_CHANNEL: () => LocalizedString
	/**
	 * Ukryj SSID
	 */
	AP_HIDE_SSID: () => LocalizedString
	/**
	 * Liczba klientów
	 */
	AP_CLIENTS: () => LocalizedString
	/**
	 * Maksymalna liczba klientów
	 */
	AP_MAX_CLIENTS: () => LocalizedString
	/**
	 * Lokalny adres IP
	 */
	AP_LOCAL_IP: () => LocalizedString
	/**
	 * Skanuj sieci WiFi
	 */
	NETWORK_SCAN: () => LocalizedString
	/**
	 * uśpiony
	 */
	IDLE: () => LocalizedString
	/**
	 * zostało utracone.
	 */
	LOST: () => LocalizedString
	/**
	 * Skanuję
	 */
	SCANNING: () => LocalizedString
	/**
	 * Skanuj ponownie
	 */
	SCAN_AGAIN: () => LocalizedString
	/**
	 * Skaner sieci WiFi
	 */
	NETWORK_SCANNER: () => LocalizedString
	/**
	 * Brak sieci WiFi w zasięgu
	 */
	NETWORK_NO_WIFI: () => LocalizedString
	/**
	 * pozostaw puste aby wyłączyć WiFi
	 */
	NETWORK_BLANK_SSID: () => LocalizedString
	/**
	 * Moc nadawania
	 */
	TX_POWER: () => LocalizedString
	/**
	 * Nazwa w sieci
	 */
	HOSTNAME: () => LocalizedString
	/**
	 * Wyłącz tryb usypiania WiFi
	 */
	NETWORK_DISABLE_SLEEP: () => LocalizedString
	/**
	 * Używaj zmniejszonej przepustowości WiFi
	 */
	NETWORK_LOW_BAND: () => LocalizedString
	/**
	 * Włącz wsparcie dla mDNS
	 */
	NETWORK_USE_DNS: () => LocalizedString
	/**
	 * Włącz wsparcie dla IPv6
	 */
	NETWORK_ENABLE_IPV6: () => LocalizedString
	/**
	 * Użyj stałego adresu IP
	 */
	NETWORK_FIXED_IP: () => LocalizedString
	/**
	 * Brama
	 */
	NETWORK_GATEWAY: () => LocalizedString
	/**
	 * Maska podsieci
	 */
	NETWORK_SUBNET: () => LocalizedString
	/**
	 * Serwery DNS
	 */
	NETWORK_DNS: () => LocalizedString
	/**
	 * Adres {0}
	 */
	ADDRESS_OF: (arg0: unknown) => LocalizedString
	/**
	 * Administrator
	 */
	ADMIN: () => LocalizedString
	/**
	 * Gość
	 */
	GUEST: () => LocalizedString
}

export type Formatters = {}
